### PR TITLE
Adjusting translater

### PR DESCRIPTION
**Pull request by cl3i550n**

### CODE REVIEW

**Comment by outsider31000** [comment]
image
this is a global which you already have in client , if the translation file and config are a shared script you dont need to have 2, only in one file is needed, you wither do that or add a local to each each file you use.

please leave all translations as default to `English`

**Comment by cl3i550n** [comment]
> this is a global which you already have in client , if the translation file and config are a shared script you dont need to have 2, only in one file is needed, you wither do that or add a local to each each file you use.

Sorry, I didn't understand correctly, it's because there are specific calls for translation in these files.
I changed to English default too.

**Comment by outsider31000** [comment]
image
  you are calling this twice as a global when the file is shared , you either add a local to each and one of them or remove from one of the files.

**Comment by outsider31000** [comment]
no need to have in server and client as global since its a shared the translation and config
 file understand ?

**Pull request merged**
